In [1]:
import numpy as np

# 1D Array

In [2]:
a = np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

#2D Array

In [4]:
b = np.array([[1,2,3,4],[5,6,7,8]])

In [5]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Attributes Of Numpy

#Shape

In [6]:
a.shape

(4,)

In [7]:
b.shape

(2, 4)

#Datatype

In [8]:
a.dtype

dtype('int32')

In [9]:
print(a.dtype)

int32


In [10]:
print(b.dtype)

int32


#Itemsize

In [11]:
print(a.itemsize)

4


In [12]:
print(b.itemsize)

4


Dimensions

In [13]:
a.ndim

1

In [14]:
b.ndim

2

Creating an Array

In [15]:
x = np.arange(1,11)

In [16]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Reshape

In [17]:
x.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [18]:
lst = [1,2.5,'Rahul',True]
y = np.array(lst)
print(y)

['1' '2.5' 'Rahul' 'True']


Empty

In [19]:
a1 = np.empty((3,2))

In [20]:
a1

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

a1 = np.empty((3,2),dtype='int32')

In [21]:
a1 = np.empty((3,2),dtype='int32')

In [22]:
a1

array([[1158752304,        547],
       [         0,          0],
       [    131074,          0]])

# Zeros

In [23]:
a2 = np.zeros((3,2))

In [24]:
a2

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
a2 = np.zeros((3,2),dtype='int')

In [26]:
a2

array([[0, 0],
       [0, 0],
       [0, 0]])

# Ones

In [27]:
a3 = np.ones((3,2),dtype="int")

In [28]:
a3

array([[1, 1],
       [1, 1],
       [1, 1]])

In [29]:
a3 = np.ones((2,3),dtype='int')

In [30]:
a3

array([[1, 1, 1],
       [1, 1, 1]])

# Diagonal 1

In [31]:
a4 = np.eye((4))

In [32]:
a4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Same Data In 2D Array

In [33]:
a5 = np.full((3,3),10)

In [34]:
a5

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

# Linespace

In [35]:
a6 = np.linspace(1,5,10)

In [36]:
a6

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [37]:
a7 = np.linspace(1,5,3)

In [38]:
a7

array([1., 3., 5.])

In [39]:
np.array(np.random.randn(5), dtype='int')

array([ 0,  1,  0, -2,  0])

In [40]:
np.array(np.random.randn(5))

array([-0.79771593, -2.66393002, -1.00107653,  0.43897671,  0.15825537])

In [41]:
np.array(np.random.randn(5))

array([ 1.59524396, -1.3526409 , -1.30005033,  1.28530913,  1.45839379])

In [42]:
np.random.randint(50,15)

ValueError: Range cannot be empty (low >= high) unless no samples are taken

In [ ]:
np.random.randint(15,50)

In [ ]:
np.random.randint(15,50,size=(3,2))

In [ ]:
np.random.randint(15,50,size=(3,))

In [ ]:
np.random.random

In [ ]:
np.random.random(size=(10,))

In [ ]:
np.random.choice(['a','b'],6)

In [ ]:
p=np.random.choice(['a','b'],1000)

In [ ]:
np.unique(p,return_counts=True)

In [ ]:
p1 = np.random.choice(['a','b'],1000,p=[0.3,0.7])

In [ ]:
p1

In [ ]:
np.unique(p1,return_counts=True)

In [ ]:
# Array Concanicate
np.array([[1,2,3],[5,6,7]]).reshape(6,)

In [ ]:
#3D Array Creation
np.random.randn(24).reshape(3,2,4)

In [ ]:
x[2:4]

# Indexing

In [ ]:
x

In [ ]:
x[::-1]

# Boolean Indexing

In [ ]:
x > 5

In [ ]:
x[x>5]

# Vectorization

In [ ]:
x + 13

In [ ]:
x

In [ ]:
x(5)

In [ ]:
x[5]

In [ ]:
np.add(x,5)

In [ ]:
np.substract(x,2)

In [ ]:
y = np.arange(12,31,2)

In [ ]:
y

In [ ]:
print(y.size)

In [ ]:
np.multiply(x,y)

In [ ]:
print(x.size)

In [ ]:
np.divide(y,2)

In [ ]:
np.divide(y,2,dtype='int32')

In [ ]:
#Sqaure Root Function
np.sqrt(y)

In [ ]:
np.sort(x)

In [ ]:
y

In [43]:
y

array(['1', '2.5', 'Rahul', 'True'], dtype='<U32')

In [44]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
x.sum()

55

In [46]:
x.sum(axis=0)

55

In [47]:
x.sum(axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [48]:
x.max

<function ndarray.max>

In [49]:
x.max()

10

In [50]:
x.min()

1

In [51]:
x.median

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [52]:
x.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [53]:
np.median(x)

5.5

In [54]:
np.mean(x)

5.5

In [55]:
x.mean()

5.5

In [56]:
y.var()

TypeError: cannot perform reduce with flexible type

In [57]:
np.var(x)

8.25

In [58]:
np.sd(x)

AttributeError: module 'numpy' has no attribute 'sd'

In [59]:
np.std(x)

2.8722813232690143

In [60]:
np.array_equal(x,y)

False

# Broadcasting

In [64]:
#Broadcating
a1 = np.array([[1,2,3],[3,4,5]])

In [66]:
a2 = np.array([1,2,6])
a1 +a2

array([[ 2,  4,  9],
       [ 4,  6, 11]])

# Cross Product And Dot Product

In [68]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[2,3],[4,5]])

In [70]:
a3 = np.array(3)

In [71]:
# Cross Product
a1 * a2

array([[ 2,  6],
       [12, 20]])

In [72]:
# Dot Product
np.dot(a1,a2)

array([[10, 13],
       [22, 29]])

# How To Detect Outlier

In [73]:
home = np.array([10,15,20,25,30,55,60,140,220])

In [74]:
np.mean(home)

63.888888888888886

In [75]:
np.median(home)

30.0

In [77]:
q1 = np.quantile(home,0.25)

In [78]:
q1

20.0

In [79]:
q3 = np.quantile(home,0.75)
q3

60.0

In [80]:
iqr = q3 - q1
iqr

40.0

In [81]:
lower_whisker = q1 -1.5*iqr
lower_whisker

-40.0

In [82]:
upper_whisker = q3 + 1.5*iqr
upper_whisker

120.0

# Reducing Skewness

In [85]:
from scipy.stats import skew
skew(home)

1.4135284762183122

In [84]:
skew(home)

1.4135284762183122

 Decimal Value -0.5 To 0.5 Normally Skewed
 <-0.5 Negatively Skewed
 >0.5 Positive Skewed

In [86]:
home.len()

AttributeError: 'numpy.ndarray' object has no attribute 'len'

In [87]:
home

array([ 10,  15,  20,  25,  30,  55,  60, 140, 220])

In [88]:
skew(home[0:7])

0.6172335454881781

In [89]:
home1 = np.sqrt(home)

In [90]:
home1

array([ 3.16227766,  3.87298335,  4.47213595,  5.        ,  5.47722558,
        7.41619849,  7.74596669, 11.83215957, 14.83239697])

In [91]:
skew(home1)

0.9857391908405431

In [92]:
home2 = np.cbrt(home)
home2

array([2.15443469, 2.46621207, 2.71441762, 2.92401774, 3.10723251,
       3.80295246, 3.91486764, 5.1924941 , 6.03681074])

In [93]:
skew(home2)

0.8090007421354857

In [94]:
home3 = np.log(home)
home3

array([2.30258509, 2.7080502 , 2.99573227, 3.21887582, 3.40119738,
       4.00733319, 4.09434456, 4.94164242, 5.39362755])

In [95]:
skew(home3)

0.41024513172945987

In [96]:
np.concatenate(x,y)

TypeError: only integer scalar arrays can be converted to a scalar index

In [97]:
np.concatenate(x,home)

TypeError: only integer scalar arrays can be converted to a scalar index

In [98]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])